typography_spectrum: 0.4206198917236179
color:
  brandColors:
    - '#603813'
    - '#000000'
    - '#ffffff'
    - '#c49a6c'
    - '#fcee02'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: kntmfg.biz
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: K & T Manufacturing
description: Origin of the maker 2 mass movement
purpose: []
