name: kntmfg.biz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4206198917236179
title: K & T Manufacturing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#603813'
    - '#000000'
    - '#ffffff'
    - '#c49a6c'
    - '#fcee02'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
