name: kntmfg.biz
favicon: null
layout_spectrum: 0.7408392624929547
typography_spectrum: 0.4206198917236179
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7754447648767382
  lightness: 0.23403220414184034
  saturation: 0.6669215760193765
  rhythmicContrast: 0.5579495111014694
purpose: []
