name: kntmfg.biz
favicon: null
layout_spectrum: 0.24476
typography_spectrum: 0.4206198917236179
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#054779'
    - '#ff991f'
    - '#ff3743'
    - '#000000'
    - '#fff9f1'
  brandStrength: 0.8125
  lightness: 0.23403220414184034
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
